### ISSUE TITLE
Won't Load: MouseCursor References

### ISSUE THREAD

**Issue by jbryanh** [Enough-Software/enough_platform_widgets#1]
Wanted to try it out.  But got about 50 errors, the first 20 were missing MouseCursor for every widget.  Maybe you're trying to get compatible with web and broke apps.

**Comment by robert-virkus** [comment]
Thanks for the report, enough_platform_widgets is indeed compatible with Flutter web.

What Flutter version are you using? Flutter 2.5.x is supported. 

Can you post the compile error you are facing?

**Comment by robert-virkus** [comment]
Closing as assumed fixed
