### ISSUE TITLE
Build error due to multiple import

### ISSUE THREAD

**Issue by DanielSmith1239** [Enough-Software/enough_platform_widgets#12]
I'm getting the following error: 
`Error: 'PlatformListTile' is exported from both 'package:enough_platform_widgets/src/platform/platform_list_tile.dart' and 'package:flutter_platform_widgets/src/platform_list_tile.dart'.`

**Comment by dab246** [comment]
- I had the same problem. I went back to using version `0.6.0` to avoid this error and it worked.
- Please fix it at the earliest. Thanks.

**Comment by robert-virkus** [comment]
Hi guys, thanks for the report. Until this is fixed, you can also fix it by hiding PlatformListTile from either source, e.g. 

```dart
import 'package:enough_platform_widgets/enough_platform_widgets.dart' hide PlatformListTile;
```

**Comment by robert-virkus** [comment]
Thanks, fixed this problem by renaming the previous PlatformListTile to SelectablePlatformListTile in enough_platform_widgets!
