### ISSUE TITLE
Make `PlatformSnackApp` extend `PlatformApp`

### ISSUE THREAD

**Issue by jaredsburrows** [Enough-Software/enough_platform_widgets#14]
Have `PlatformSnackApp` extend `PlatformApp` to ensure the themes are inherited.

**Comment by robert-virkus** [comment]
What problem would you like to solve? The material app will use the given `materialTheme` or `materialDarkTheme`, the cupertino app the `cupertinoTheme`.

**Comment by tikal** [comment]
Agree that is not too clear how to make `PlatformSnackApp` work with `PlatformTheme`

**Comment by robert-virkus** [comment]
Closing as won't do
