### ISSUE TITLE
Multiple build errors 

### ISSUE THREAD

**Issue by DanielSmith1239** [Enough-Software/enough_platform_widgets#4]
Hello, I'm trying to use this library and I'm getting the following build errors:
- Error: 'showPlatformDatePicker' is exported from both 'package:flutter_platform_widgets/src/platform_date_picker.dart' and 'package:enough_platform_widgets/src/platform/platform_time_picker.dart'. (../…/lib/enough_platform_widgets.dart:4)
- Error: The argument type 'Widget Function(BuildContext, {void Function()? onStepCancel, void Function()? onStepContinue})?' can't be assigned to the parameter type 'Widget Function(BuildContext, ControlsDetails)?'. (../…/platform/platform_stepper.dart:43)
-  Error: The argument type 'Widget Function(BuildContext, {void Function()? onStepCancel, void Function()? onStepContinue})?' can't be assigned to the parameter type 'Widget Function(BuildContext, ControlsDetails)?'. (../…/platform/platform_stepper.dart:54)

**Comment by robert-virkus** [comment]
Thanks for the report, this is now fixed with release v0.3.0.

Please close if this works for you!

**Comment by DanielSmith1239** [comment]
Looks like it works, thanks!
